const hashtagMapping = {
  '#labour': '#labor',
  '#sonic_meditation': '#sonic_meditations',
  '#tracksuits': '#tracksuit',
  '#umbrella': '#umbrellas',
  '#monuments': '#monument',
  '#forest': '#shockforest',
  '#industralization': '#industrialization',
  '#weapons': '#weapon',
  '#colons': '#colonialism',
  '#water': '#waves',
  '#infilm': '#film',
  '#trial_error': '#explosions',
  '#foundation': '#hembrug',
  '#warmth': '#belonging',
  '#JUNGLE': '#canopy',
  '#background': '#hembrug',
  '#danger': '#violence',
  '#shock_forest': '#shockforest',
  '#weapon': '#weapons',
  '#Umbrellas': '#umbrellas',
  '#shipnames': '#ship_names',
  '#SHIP_NAMES': '#ship_names',
  '#documentary': '#film',
  '#leemans': '#shockforest',
  '#petermarcuse': '#labor',
  '#enschede': '#explosions',
  '#toxicity': '#traces',
  '#humans': '#traces',
  '#nimh': '#archive',
  '#social_history': '#labor',
  '#canopy': '#umbrellas',
  '#gemeentearchief': '#archive',
  '#tree': '#trees',
  '#eurometal': '#eurometaal',
  '#map': '#maps',
  '#jungle': '#canopy',
  '#military': '#militarization',
  '#ad': '#promos',
  '#trade': '#movement',
  '#300years': '#anniversary',
  '#zwartboek': '#blackbook',
  '#weapons_museum': '#weapons',
  '#Ship_names': '#ship_names',
  '#northseacanal': '#noordzeekanaal',
  '#craftsmanship': '#craft',
  '#oneness': '#belonging',
  '#europersmagazine': '#newspaper',
  '#acousticruins': '#ruins',
  '#dirt': '#soil',
  '#clay': '#soil',
  '#geographies': '#maps',
  '#wave': '#waves',
  '#posthuman': '#traces',
  '#guns': '#weapons',
  '#tunnel': '#hethem',
  '#photo': '#film',
  '#sonicweapons': '#weapons',
  // '#sfgroom': '#maquette',
  '#sfgroom': '#maps',
  '#participation': '#hembrug',
  '#ship': '#ship_names',
  '#spaces': '#hethem',
  '#countermonument': '#monument',
  '#assemblyline': '#industrialization',
  '#radical': '#activism',
  '#sales': '#promos',
  '#implosion': '#explosions',
  '#land': '#soil',
  '#score': '#scores',
  '#countermonuments': '#monument',
  '#monumental': '#monument',
  '#buoy': '#wavesensor',
  '#remnants': '#ruins',
  '#protest': '#activism',
  '#sfg': '#shockforestgroup',
  '#contamination': '#toxicity',
  'AI': 'ai',
  '#arms': '#weapons',
  '#maproom': '#maps',
  '#protests': '#activism',
  '#SaturdaynightsinZaandam': null,
  '#lunch': null,
  '#commute': null,
  // '#transform': '#reverb',
  '#transform': null,
  '#zanditsdayout': null,
  '#haiku': null,
  '#botsholes': null,
  '#news': null,
  '#drinking': null,
  '#definition': null,
  '#topotijdreis': null,
  '#muurkrant': null,
  '#aurevoir': null,
  '#zaandits': null,
  '#inspiration': null,
  '#planted': null,
  '#findingpantxo': null,
  '#names': null,
  '#gluematic': null,
  '#toilet': null,
  '#testing': null
}

// ignore - Ignore hashtag
// map - Change hashtag into new hashtag
// unignore - Remove ignored hashtag
// unmap - Remove hashtag mapping

function formatHashtag (hashtag) {
  const mappedHashtag = hashtagMapping[hashtag]
  if (mappedHashtag === undefined) {
    return hashtag
  } else {
    return mappedHashtag
  }
}

module.exports = {
  hashtag: formatHashtag,
  hashtagMapping
}
